package com.example.jingtao.mapper;

import com.example.jingtao.entity.SchoolNews;
import com.example.jingtao.entity.SchoolNewsExample;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SchoolNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int countByExample(SchoolNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int deleteByExample(SchoolNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String title);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int insert(SchoolNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int insertSelective(SchoolNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    List<SchoolNews> selectByExampleWithBLOBs(SchoolNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    List<SchoolNews> selectByExample(SchoolNewsExample example);

    List<SchoolNews> getAllSchoolNews();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    SchoolNews selectByPrimaryKey(String title);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SchoolNews record, @Param("example") SchoolNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SchoolNews record, @Param("example") SchoolNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SchoolNews record, @Param("example") SchoolNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SchoolNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SchoolNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SchoolNews record);
}