package com.example.jingtao.mapper;

import com.example.jingtao.entity.UserInf;
import com.example.jingtao.entity.UserInfExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface UserInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int countByExample(UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int deleteByExample(UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int insert(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int insertSelective(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    List<UserInf> selectByExample(UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    UserInf selectByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserInf record, @Param("example") UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserInf record, @Param("example") UserInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInf record);
}