package com.example.jingtao.entity;

public class Token {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.token
     *
     * @mbggenerated
     */
    private String token;

    public Token(String token, String sessionKey, String openid, String creatTime) {
        this.token = token;
        this.sessionKey = sessionKey;
        this.openid = openid;
        this.creatTime = creatTime;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.session_key
     *
     * @mbggenerated
     */
    private String sessionKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column token.create_time
     *
     * @mbggenerated
     */
    private String creatTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.token
     *
     * @return the value of token.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.token
     *
     * @param token the value for token.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.session_key
     *
     * @return the value of token.session_key
     *
     * @mbggenerated
     */
    public String getSessionKey() {
        return sessionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.session_key
     *
     * @param sessionKey the value for token.session_key
     *
     * @mbggenerated
     */
    public void setSessionKey(String sessionKey) {
        this.sessionKey = sessionKey == null ? null : sessionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.openid
     *
     * @return the value of token.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.openid
     *
     * @param openid the value for token.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column token.create_time
     *
     * @return the value of token.create_time
     *
     * @mbggenerated
     */
    public String getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column token.create_time
     *
     * @param creatTime the value for token.create_time
     *
     * @mbggenerated
     */
    public void setCreatTime(String creatTime) {
        this.creatTime = creatTime;
    }
}